name: MosaicApp
options:
  bundleIdPrefix: com.mosaic
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
  groupSortPosition: top
targets:
  MosaicApp:
    type: application
    platform: iOS
    sources:
      - path: MosaicApp
        excludes:
          - "Info.plist"
    info:
      path: MosaicApp/Info.plist
      properties:
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
        UISupportedInterfaceOrientations~iPhone:
          - UIInterfaceOrientationPortrait
        UISupportedInterfaceOrientations~iPad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UILaunchScreen: {}
        NSAppTransportSecurity:
          NSAllowsArbitraryLoads: true
    settings:
      base:
        SWIFT_VERSION: "5.9"
        PRODUCT_BUNDLE_IDENTIFIER: com.liulingfeng.MosaicApp
        PRODUCT_NAME: "知合 Mosaic"
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: 1
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        CODE_SIGN_STYLE: Automatic
